NGSimulator {
  seed = 123
  outputDirectory = "outputs/netgamesim"

  Graph {
    directed = false
    directionality = "undirected"
    weighted = false
  }

  OutputGraphRepresentation {
    format = "dot"
    contentType = "graphviz"
  }

  NetModel {
    distanceSpreadThreshold = 0.05
    numberOfExperiments = 1
    perturbationCoefficient = 0.0
    dissimulationCoefficient = 0.0
    distanceCoefficient = 0.2
    edgeProbability = 0.2
    statesTotal = 8
    desiredReachabilityCoverage = 1.0
    numberOfWalks = 10
    maxBranchingFactor = 4
    maxDepth = 3
    maxProperties = 5
    propValueRange = 10
    actionType = 5
    actionRange = 5
    connectedness = 2
    maxWalkPathLengthCoeff = 2
    graphWalkTerminationPolicy = ${NGSimulator.Constants.MaxPathLength}
    graphWalkNodeTerminationProbability = 0.001
  }

  CostRewards {
    Budget = 1000.0
    costOfDetection = 0.2
    serviceRewardProbability = 0.3
    serviceReward = 10.0
    servicePenalty = 3.0
    targetNodeValue = 5
    targetNodeLowPenalty = 1
    targetNodeHighPenalty = 2
  }

  Constants {
    MaxPathLength = "maxpathlength"
    UntilCycle = "untilcycle"
    All = "all"
  }
}
